### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by jqtrde** [propublica/schooner-tk#3]
Running `OSX 10.10.3` and `OpenCV 2.4.11` via homebrew.

I'm trying to build with `make`, but am receiving the following error:

```
clang++ -I/usr/local/Cellar/gdal/1.11.2_1/include -g -std=c++11 -stdlib=libc++ -I/usr/local/Cellar/opencv/2.4.11_1/include/opencv -I/usr/local/Cellar/opencv/2.4.11_1/include  -I./src/    src/schooner-contrast.cc  -L/usr/local/Cellar/gdal/1.11.2_1/lib -lgdal -L/usr/local/Cellar/opencv/2.4.11_1/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab  -std=c++11 -stdlib=libc++ -o src/schooner-contrast

src/schooner-contrast.cc:4:10: fatal error: 'opencv2/imgproc.hpp' file not found
#include <opencv2/imgproc.hpp>
         ^
1 error generated.
```

I'll trade you documentation for helping me get this installed :grinning:

**Comment by thejefflarson** [comment]
Yeah it is in sore need of docs, among other improvements. So, it's a
slight pain, but you have to install the development version of opencv:

brew install opencv --devel --without-opencl

It's mentioned here, but I have to write a proper readme:

https://propublica.github.io/schooner-tk/man/schooner-stitch.1.html

The without-opencl is necessary, because we found that the opencl
drivers on osx would crash the whole computer.

I could probably backport or ifdef the opencv bits, but they promised
3.0.0 like last year, and new software is better than old so I'm sorta
in favor of keeping it this way.

Please do let me know if it works for you! I'm excited for someone else
to kick the tires.

j:

**Comment by jqtrde** [comment]
Hey thanks for the quick response!

I'll take a crack at it tonight. Hopefully should have a PR for you tomorrow.
